credentials:
  usernames:
    richmondyeboah:
      email: richmondyeboah299@gmail.com
      name: Richmond Yeboah
      # password should be hashed and not stored in plaintext
      password_hash: #statistics299
cookie:
  expiry_days: 30
  key: some_signature_key  # Must be a string
  name: some_cookie_name
