credentials:
  usernames: cactus299
    admin: Richmond Yeboah
      email: richmondyeboah299@gmail.com
      password: statistics299

cookie:
  expiry_days: 30
  key: some_random_key

preauthorized:
  emails: 
    - richmondyeboah299@gmail.com
